import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Layout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <main>
      <div>{children}</div>
    </main>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="valentine">
      <body>{children}</body>
    </html>
  );
}
